name: hacker
favicon: null
layout_spectrum: 0.1979792902711779
typography_spectrum: 0.5748276163358241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.198263336205855
purpose:
  - name: shares
    item: null
    url: null
